---
databases:
  summitcdb:
    schema: "/Users/fred3m/code/lsst/rubintv_analysis_service/data/summit.yaml"
    url: "sqlite:////Users/fred3m/temp/visitDb/summit.db"
#butler:
#  repo: /repos/main
#efd:
# url: connection info here