---
locations:
  summit: "postgresdb01.cp.lsst.org"
  usdf: "usdf-summitdb.slac.stanford.edu"
schemas:
  cdb_latiss: cdb_latiss.yaml
  cdb_lsstcomcam: cdb_lsstcomcam.yaml
  cdb_lsstcomcamsim: cdb_lsstcomcamsim.yaml
#  cdb_lsstcam: cdb_lsstcam.yaml
repos:
  - /repo/main
  - embargo_or4
#efd:
# url: connection info here
