---
name: docs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_sphinx_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Need to clone everything for the git tags.
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: "setup.cfg"

      - name: Update pip/wheel infrastructure
        run: |
          python -m pip install --upgrade pip
          pip install wheel

      - name: Build and install
        run: pip install -v -e .

      - name: Show compiled files
        run: ls python/lsst/rubintv/analysis/service

      - name: Install documenteer
        run: |
          pip install 'sphinx<7'
          pip install 'documenteer[pipelines]==0.8.2'

      - name: Build documentation
        working-directory: ./doc
        run: package-docs build
